### ISSUE TITLE
锦鲤助力不成功

### ISSUE THREAD

**Issue by cuncun-edg** [HarbourJ/HarbourToulu#1]
![image](https://user-images.githubusercontent.com/77426305/167769188-b6087478-85ee-4b7e-b97b-a691e4089eff.png)

**Comment by HarbourJ** [comment]
> ![image](https://user-images.githubusercontent.com/77426305/167769188-b6087478-85ee-4b7e-b97b-a691e4089eff.png)

本地log已经暂停更新了。
