### ISSUE TITLE
ld-linux-aarch64.tar.gz小问题

### ISSUE THREAD

**Issue by pujie1216** [HarbourJ/HarbourToulu#11]
由于 3.0 release下没有上传 ld-linux-aarch64.tar.gz 该文件,首次检查依赖会出错,如果 ld-linux-aarch64.tar.gz 该文件只会上传到 2.0 release ,可以暂时本地修改 jd_check_dependent.py 该文件修复错误,编辑该 py 文件,搜索 `if download(version, "ld-linux-aarch64.tar.gz"):` 该代码,将`version`改为`"2.0"`(带引号),保存后重新运行 py 文件即可,另一种办法就是等程序员上传 ld-linux-aarch64.tar.gz 该文件到 3.0 release 下

**Comment by HarbourJ** [comment]
已提交至release3.0
