### ISSUE TITLE
大佬求助，拉库完运行报错

### ISSUE THREAD

**Issue by XWY-kawayi** [HarbourJ/HarbourToulu#3]
大佬，引用jd_sign失败，这个文件是哪个啊，jd_sign.so还是另外的，报下面的错误
 from jd_sign import *
ImportError: Error relocating /ql/data/scripts/HarbourJ_HarbourToulu_main/jd_sign.so: _Py_CheckRecursionLimit: symbol not found

**Comment by happy-Z** [comment]
一样的问题

**Comment by zyqyz** [comment]
下面并没有使用，我直接注释了，可以正常执行，可能是作者忘记注释了

**Comment by gclm** [comment]
timeout: failed to run command ‘jd_sign_x86.so’: Permission denied

**Comment by Silentely** [comment]
问题已解决、Py版本修改为3.8.13正常了
—————————————-
同，难道是py版本还是青龙版本的问题？

 Traceback (most recent call last):
  File "/ql/data/scripts/HarbourJ_HarbourToulu_main/jd_wxCompleteInfo.py", line 30, in <module>
    from jd_sign import *
ImportError: Error relocating /ql/data/scripts/HarbourJ_HarbourToulu_main/jd_sign.so: _Py_CheckRecursionLimit: symbol not found

**Comment by HarbourJ** [comment]
jd_sign.so依赖文件主要与Py版本有关，拉完库请先运行一键依赖安装脚本(jd_check_dependent.py)， 大概率可以解决所遇到的问题。
