### ISSUE TITLE
N5105 docker上jd_sign.so报错

### ISSUE THREAD

**Issue by VwEl** [HarbourJ/HarbourToulu#5]
各种版本都试过了，提示有以下三种
①：Exec format error
②：unsupported relocation type 1026
③：_Py_CheckRecursionLimit: symbol not found

**Comment by kaisyaliu** [comment]
J1900黑晖Docker报错_Py_CheckRecursionLimit: symbol not found

**Comment by HarbourJ** [comment]
> J1900黑晖Docker报错_Py_CheckRecursionLimit: symbol not found

没有群辉系统做测试，可以在tg找我一下，我测试一下是什么问题。
