### ISSUE TITLE
HarbourJ库依赖一键安装失败

### ISSUE THREAD

**Issue by aefa6** [HarbourJ/HarbourToulu#7]
jd_sign-linux-amd64.tar.gz下载成功
jd_sign.so
依赖安装/更新失败,请前往https://github.com/HarbourJ/HarbourToulu/blob/main/README.md,查看依赖安装教程

**Comment by aefa6** [comment]
试了好几次都这样

**Comment by jtmyd-top** [comment]
https://github.com/HarbourJ/HarbourToulu/blob/main/README.md，404了

**Comment by HarbourJ** [comment]
依赖一键安装失败，大概率是无法访问到远程redis授权服务器，请把代理规则加一个白名单，具体可到TG找：@HarbourJ
